# -*- coding: utf-8 -*-
"""Examen modulo 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUoUsEdMKyBki7iEgNHT16q3W2nG_nIo

# Preparación y Lección 1: Datos y Fundamentos
"""

#Primero importamos las librerías necesarias y generamos los datos. Definimos el problema como Regresión Supervisada porque queremos predecir un valor numérico continuo (el monto de compra).reación del dataset

# Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score

# Generar Dataset Ficticio (Reemplaza esto con pd.read_csv('tus_datos.csv'))
np.random.seed(42)
n = 1000
datos = pd.DataFrame({
    'edad': np.random.randint(18, 70, n),
    'tiempo_sitio_min': np.random.uniform(1, 60, n),
    'paginas_vistas': np.random.randint(1, 20, n),
    'categoria_fav': np.random.choice(['Tecnologia', 'Ropa', 'Hogar'], n),
    # El gasto total tiene una relación lineal con las variables para simular la realidad
    'gasto_total': np.zeros(n)
})
datos['gasto_total'] = (datos['edad']*1.5) + (datos['tiempo_sitio_min']*3) + (datos['paginas_vistas']*5) + np.random.normal(0, 20, n)

# Mostrar los primeros registros
print(datos.head())

#Ya con el dataset generado procedemos al correspondiente avance de las lecciones.

"""#Lección 3 y 2: Preprocesamiento y División de Datos"""

#Manejaremos variables categóricas, escalaremos numéricas y dividiremos en entrenamiento y validación.

# Separar características (X) y objetivo (y)
X = datos.drop('gasto_total', axis=1)
y = datos['gasto_total']

# División en entrenamiento y prueba (Lección 2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocesamiento (Lección 3)
num_features = ['edad', 'tiempo_sitio_min', 'paginas_vistas']
cat_features = ['categoria_fav']

preprocesador = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features), # Estandarización
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_features) # Codificación categórica
    ])

# Preprocesar los datos
X_train_prep = preprocesador.fit_transform(X_train)
X_test_prep = preprocesador.transform(X_test)

"""#Lección 4 y 6: Regresión Lineal y Métricas de Desempeño"""

#Entrenamos el modelo básico y calculamos las métricas.
#A nivel matemático, recuerda que el modelo busca minimizar los errores basándose en estas fórmulas:
#Error Absoluto Medio (MAE)
#Raíz del Error Cuadrático Medio (RMSE)
#Coeficiente de Determinación (R^2): Indica qué porcentaje de la varianza explica el modelo


# Entrenar Regresión Lineal
modelo_lr = LinearRegression()
modelo_lr.fit(X_train_prep, y_train)

# Predicciones
y_pred_lr = modelo_lr.predict(X_test_prep)

# Métricas (Lección 6)
def evaluar_modelo(y_true, y_pred, nombre_modelo):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    print(f"--- Métricas {nombre_modelo} ---")
    print(f"MAE: {mae:.2f} | RMSE: {rmse:.2f} | R2: {r2:.4f}\n")
    return mae, rmse, r2

evaluar_modelo(y_test, y_pred_lr, "Regresión Lineal")

# Validación Cruzada K-Folds (Lección 2)
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores_cv = cross_val_score(modelo_lr, X_train_prep, y_train, cv=kf, scoring='r2')
print(f"R2 Promedio K-Fold CV: {scores_cv.mean():.4f}")

"""#Lección 5: Algoritmos de Clasificación (El contraste)"""

#Aquí demostramos por qué Clasificación no sirve para predecir monto, convirtiendo el problema temporalmente a "Gasto Alto" vs "Gasto Bajo".

# Crear variable objetivo simulada para clasificación
mediana_gasto = y_train.median()
y_train_class = (y_train > mediana_gasto).astype(int)
y_test_class = (y_test > mediana_gasto).astype(int)

# Entrenar KNN Clasificador
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_prep, y_train_class)
y_pred_class = knn.predict(X_test_prep)

print("Exactitud KNN Clasificación:", accuracy_score(y_test_class, y_pred_class))
print("Conclusión: KNN nos dice si gastará mucho o poco, pero no el monto exacto, perdiendo valor para estimar ingresos reales.")

"""#Lección 7 y 8: Optimización y Boosting"""

# Aplicaremos Regularización (Ridge/Lasso) usando GridSearchCV y finalmente el modelo avanzado GradientBoostingRegressor.


# Lección 7: Optimización con Ridge y GridSearchCV
parametros_ridge = {'alpha': [0.1, 1.0, 10.0, 100.0]}
grid_ridge = GridSearchCV(Ridge(), parametros_ridge, cv=5, scoring='r2')
grid_ridge.fit(X_train_prep, y_train)

print(f"Mejor hiperparámetro Ridge: {grid_ridge.best_params_}")
y_pred_ridge = grid_ridge.predict(X_test_prep)
evaluar_modelo(y_test, y_pred_ridge, "Regresión Ridge Optimizada")

# Lección 8: Algoritmo de Boosting
modelo_gb = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
modelo_gb.fit(X_train_prep, y_train)

y_pred_gb = modelo_gb.predict(X_test_prep)
evaluar_modelo(y_test, y_pred_gb, "Gradient Boosting")

# Visualización comparativa
plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred_lr, alpha=0.5, label='Regresión Lineal')
plt.scatter(y_test, y_pred_gb, alpha=0.5, color='red', marker='x', label='Gradient Boosting')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2, label='Predicción Perfecta')
plt.xlabel("Gasto Real")
plt.ylabel("Gasto Predicho")
plt.title("Comparación de Modelos")
plt.legend()
plt.show()

## Análisis de Optimización (Regresión Ridge)
#Tras aplicar GridSearchCV para encontrar el mejor hiperparámetro, el modelo determinó que el valor óptimo de penalización es `alpha: 1.0`. Esto significa que aplicó una regularización moderada, logrando un excelente equilibrio que evita el sobreajuste sin perder capacidad predictiva.

#**Métricas obtenidas:**
#* **R2 (0.9055):** El modelo logra explicar aproximadamente el 90.5% de la varianza en el comportamiento de gasto de los clientes. Es un nivel de ajuste sobresaliente.
#* **RMSE (20.45) y MAE (16.49):** Nos indican que, en promedio, nuestras predicciones de gasto se desvían entre 16 y 20 unidades monetarias del valor real, un margen de error bastante aceptable dependiendo de la escala de ventas del negocio.

### Análisis de Gradient Boosting
#Implementamos un modelo de ensamble avanzado (Gradient Boosting), el cual suele ser muy poderoso para capturar relaciones no lineales y complejas en los datos.

#Sin embargo, al observar las métricas, obtuvimos un **R2 de 0.8832** y un **RMSE de 22.73**. Si bien es un desempeño bastante sólido, resulta ligeramente inferior al modelo de regresión lineal regularizado (Ridge). Esto se debe a la naturaleza de nuestro conjunto de datos: las variables predictoras (como la edad o el tiempo en el sitio) tienen una relación directa y lineal con la variable objetivo. En escenarios fuertemente lineales, los modelos tradicionales bien ajustados a menudo logran igualar o superar a los algoritmos basados en árboles de decisión.

"""#Conclusiones Finales y Eleccion de Modelo.

Conclusión Final y Elección del Modelo
Observando la gráfica de "Comparación de Modelos", es evidente que tanto las predicciones del modelo lineal (puntos azules) como las del Gradient Boosting (cruces rojas) se alinean estrechamente con la línea negra de "Predicción Perfecta", lo que demuestra que ambos aprendieron patrones útiles.

Sin embargo, basándonos en un análisis integral, **el modelo seleccionado como final para este proyecto es la Regresión Ridge Optimizada (`alpha=1.0`)**.

**Justificación técnica y de negocio:**
1. **Mejor desempeño predictivo:** Posee el R2 más alto (0.9055) y el margen de error más bajo (RMSE de 20.45).
2. **Robustez:** La regularización L2 aplicada (Ridge) nos asegura que el modelo penaliza pesos muy altos, haciéndolo menos propenso al sobreajuste y más confiable al enfrentarse a nuevos clientes en el futuro.
3. **Interpretabilidad e impacto analítico:** A nivel comercial, un modelo lineal es mucho más "transparente" que una caja negra como Boosting. Podemos extraer los coeficientes para decirle exactamente al equipo de Marketing: *"Por cada minuto extra que un usuario pasa en el sitio web, su gasto aumenta en X cantidad"*. Esto permite tomar decisiones de negocio accionables, cumpliendo con el objetivo inicial del Departamento de Analítica.

Atte. Cristóbal Hernández L.
"""